workflows:
  react-web-and-mobile:
    name: React Web and Mobile Build
    max_build_duration: 60
    environment:
      node: latest
    cache:
      cache_paths:
        - $CM_BUILD_DIR/node_modules
    triggering:
      events:
        - push
        - tag
        - pull_request
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build Web
        script: |
          npm run build
      - name: Install Capacitor
        script: |
          npm install @capacitor/core @capacitor/cli
          npx cap init MyApp com.example.myapp --web-dir=build
          npm install @capacitor/android @capacitor/ios
          npx cap add android
          npx cap add ios
      - name: Build Android
        script: |
          npx cap sync android
          cd android
          ./gradlew assembleRelease
      - name: Build iOS
        script: |
          npx cap sync ios
          cd ios
          xcodebuild -workspace App.xcworkspace -scheme App -configuration Release -archivePath App.xcarchive archive
          xcodebuild -exportArchive -archivePath App.xcarchive -exportPath . -exportOptionsPlist exportOptions.plist
    artifacts:
      - build/**
      - android/app/build/outputs/**/*.apk
      - ios/App.ipa
    publishing:
      email:
        recipients:
          - user@example.com
