export const themes = {
  default: { name: 'Netflix', primary: '#E50914', background: '#000000', text: '#FFFFFF' },
   chemical: { name: 'Chemical', primary: '#1CE783', background: '#0B0C0F', text: '#FFFFFF' },
  royalBlue: { name: 'Royal Blue', primary: '#0063E5', background: '#040714', text: '#F9F9F9' },
  azureWaters: { name: 'Azure Waters', primary: '#00A8E1', background: '#0F171E', text: '#FFFFFF' },
  lavenderDreams: { name: 'Lavender Dreams', primary: '#9949D8', background: '#030328', text: '#FFFFFF' },
  minimalist: { name: 'Minimalist', primary: '#2D2D2D', background: '#FFFFFF', text: '#000000' },
  scarletFever: { name: 'Scarlet Fever', primary: '#FF0000', background: '#FFFFFF', text: '#282828' },
  oceanDepths: { name: 'Ocean Depths', primary: '#0064FF', background: '#041E42', text: '#FFFFFF' },
  sunsetOrange: { name: 'Sunset Orange', primary: '#F47521', background: '#23252B', text: '#FFFFFF' },
  emeraldForest: { name: 'Emerald Forest', primary: '#1DB954', background: '#191414', text: '#FFFFFF' },
  amethystGlow: { name: 'Amethyst Glow', primary: '#9146FF', background: '#0E0E10', text: '#EFEFF1' },
  neonPulse: { name: 'Neon Pulse', primary: '#FE2C55', background: '#000000', text: '#FFFFFF' },
  skyBlue: { name: 'Sky Blue', primary: '#0099FF', background: '#F2F2F2', text: '#000000' },
  goldenSun: { name: 'Golden Sun', primary: '#000000', background: '#FFC600', text: '#000000' },
  maroonNight: { name: 'Maroon Night', primary: '#B50000', background: '#000000', text: '#FFFFFF' },
  midnightGold: { name: 'Midnight Gold', primary: '#FBB400', background: '#000030', text: '#FFFFFF' },
  coralReef: { name: 'Coral Reef', primary: '#FF4E78', background: '#FFFFFF', text: '#000000' },
  monochrome: { name: 'Monochrome', primary: '#FFFFFF', background: '#000000', text: '#FFFFFF' },
};
